name:  Solar Site Tracking Template Form
description: Fill out this form to create a section-specific solar site business service plan.
title: "Solar Site <Site ID>, Section <section>, <high side or center> Mow, <start date>"

body:
  - type: markdown
    id: greeting
    attributes:
      value: |
        Thanks for taking the time to fill out this buisness planning issue!
        
  - type: input
    id: site-details
    attributes:
      label: Site Details
      description: Type the name/ID of the Solar Site
      placeholder: ex. NEE Interstate
    validations:
      required: false
      
  - type: input
    id: start-date
    attributes:
      label: Start Date
      description: The date that this mow began.
      placeholder: ex. Day, Month, Year
    validations:
      required: false
      
  - type: input
    id: end-date
    attributes:
      label: Finish Date
      description: The date that this mow finished.
      placeholder: ex. Day, Month, Year
    validations:
      required: false  
      
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: What section of the site is being addressed?
      options:
        - North
        - Central
        - South
    validations:
      required: true
      
  - type: dropdown
    id: side
    attributes:
      label: Mow Line
      multiple: true
      options:
        - Center line
        - High side
    
  - type: checkboxes
    id: readiness
    attributes:
      label: Fleet Readiness
      description: Confirm mechanical inspection and site organization before section-level mow.
      options:
        - label: Full inspection issues created for each LCR
        - label: LCR inspection issues complete.
          required: false
          
  - type: checkboxes
    id: mowing
    attributes:
      label: Mowing
      description: Confirm complete of mow related goals.
      options:
        - label: Rows complete.
        - label: Fence-line complete
        - label: Service and access roads complete.
        - label: Inverter open block area complete.
          required: false 
          
  - type: checkboxes
    id: trimming
    attributes:
      label: Trimmming
      description: Confirm complete of trimmer related goals.
      options:
        - label: Trimming of risers and collector boxes complete.
        - label: Trimming around inverters complete.
          required: false 
              
  - type: textarea
    id: plan_description
    attributes:
      label: Action Plan
      description: Please briefly explain the mow stategy and goal regarding this mow.
      render: shell
      
  - type: markdown
    id: code-of-conduct
    attributes:
      value: |
       ## Everyday the operators must:
       Check robot mower cabling and reductions to confirm that an LCR is clear for mowing.
       Discuss and organize remote vs. in-person scheduling and mow duties.
       Verify robot state of charge EOD.
       Post a daily screenshot of telemetry data in the comments below.
       
  - type: checkboxes
    id: terms
    attributes:
      label: Operator Code of Conduct Agreement
      description: By submitting this issue, you agree to follow our Operator Code of Conduct.
      options:
        - label: I agree to follow the operator code of conduct.
          required: true
