name: Solar Site Mow Tracking
description: Fill out the form for solar section specific service planning.
title: "Solar Site <Site ID and name> Section <name> <Center|High side> Mow, Start:<Month, Day, Year> "
labels: ["mow", "trim", "low side", "high side"]
assignees:
  - Aweesam
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Task Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: What what section of the site is being adressed?
      options:
        - North
        - Central
        - South
    validations:
      required: true
  - type: dropdown
    id: side
    attributes:
      label: Mow Line
      multiple: true
      options:
        - Center line
        - High side
        
  - type: textarea
    id: plan description
    attributes:
      label: Action Plan
      description: Please briefly explain the mow stategy and goal regarding this mow.
      render: shell
  - type: markdown
    value: |
      - Everyday the operators must:
      - Check robot mower cabling and reductions to confirm that an LCR is clear for mowing.
      - Discuss and organize remote vs. in-person scheduling and mow duties.
      - Verify robot state of charge EOD.
      - Post a daily screenshot of telemetry data in the comments below.
  - type: checkboxes
    id: terms
    attributes:
      label: Operator Code of Conduct
      description: By submitting this issue, you agree to follow our Operator Code of Conduct.
      options:
        - label: I agree to follow the operator code of conduct.
          required: true
